# docker running
sudo: required
services: 
  - docker

#build using dockerfile.dev
before_install: 
  - docker build -t krbl/docker-react -f Dockerfile.dev .

# run tests
script:
  - docker run -e CI=true krbl/docker-react npm run test

# deploy to AWS
deploy:
  provide: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-887163512152"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY